### ISSUE TITLE
Missing `operator->` in iterators

### ISSUE THREAD

**Issue by ujos** [OleksandrKvl/sbepp#28]
Could you please add `operator->` to the `sbepp::detail::forward_iterator`

**Comment by OleksandrKvl** [comment]
It's not missing, it's just not possible to have. All iterators in `sbepp` are proxy ones, their `value_type` objects don't exist in memory, they are created on the fly and returned by-value by `operator*`, there's no pointer to return in `operator->`. For this reason, C++20 doesn't require iterators to have `operator->`.

P.S. I strongly recommend you to always provide real case based motivation for feature requests. Something can be considered "missing" not just because it's absent but because it's actually needed and existing functionality is not enough.

**Comment by OleksandrKvl** [comment]
First of all, you don't need C++20 to use iterators without `operator->`, I don't know any STL function that relies on it.
Thanks for the code sample, now it's much easier to reason about. As I said, it's just not possible to have `operator->` but I don't really see a problem here. `set((*exchangesIt).name(), exch)` is not much verbose than theoretical `set(exchangesIt->name(), exch)`. You can instead iterate over `exchanges` in a range-for-loop and over `exchangesArray` manually via iterator:

```cpp
constexpr auto exchangesArray[] = { "NYSE", "CME", "CBOE" };

auto exchanges = m.exchanges();
sbepp::fill_group_header(exchanges, std::size(exchangesArray));

auto it = std::begin(exchangesArray);
for(const auto entry : exchanges){
    set(entry.name(), *it);
    ++it;
}
```

You can even iterate over both of them using index:

```cpp
constexpr auto exchangesArray[] = { "NYSE", "CME", "CBOE" };

auto exchanges = m.exchanges();
sbepp::fill_group_header(exchanges, std::size(exchangesArray));

for(std::size_t i =0; i != exchanges.size(); i++){
    set(exchanges[i].name(), exchangesArray[i]);
}
```

I'd say that the real problem here is that you're using manual loop and multiple layers of abstraction got mixed. What you really need is to `join` two views iterate over this joined view and assign the value. It's easy to achieve using `ranges` or just a handwritten function.

**Comment by ujos** [comment]
I see, thank you very much for the explanation.

BTW, I've found the following. You do not have to implement it. JFYI.

> The operator->() is a bit of an odd-ball: although it can return a non-pointer type, the resulting type would need to overload the operator->(), too!

```cpp
struct Y {
   int x;
   Y* operator->() { return this; }
};

struct X{
   Y operator->() { return {}; }
};

int main()
{
   auto x = X{};
   auto f = x->x;
}

```

Source: https://stackoverflow.com/questions/20688066/result-of-operator-yields-non-pointer-result

**Comment by OleksandrKvl** [comment]
That's actually interesting and seems that it's already used by other libraries for this exact purpose. Will try to implement it so reopening this issue.
