### ISSUE TITLE
Why not the other SBE-CPP?

### ISSUE THREAD

**Issue by haydenflinner** [OleksandrKvl/sbepp#5]
What does this implementation offer over the 'default' impl generated by RealLogic's repo? It does look like the API is considerably easier to use, but it would be good to write it out somewhere in the docs. I see the benchmarks are comparing to handwritten code rather than the competing impl, maybe it's too hard to wrest memory management from the other one?

https://github.com/real-logic/simple-binary-encoding

**Comment by OleksandrKvl** [comment]
I thought about such a comparison but then decided against it for some reason, initially I didn't want to promote this project as RealLogic's rival. However, since you are asking, I can add it :)

About benchmarks, I have both, RealLogic and hand-written SBE readers there. Let's say I am not satisfied with the interface and generated source files RealLogic provides and don't consider it as a good baseline for benchmarks. Instead, low-level, hand-written code is a perfect baseline because it has no overhead, only pure memory reads and casts.
