### ISSUE TITLE
is using this library as fast as using raw c struct?

### ISSUE THREAD

**Issue by ssh352** [OleksandrKvl/sbepp#66]
Sending raw c struct over the network is pretty fast but quite tedious.  I came across this library and thought it could be very fast, would it be as fast as raw c struct and in what cases it won't be as fast? thanks!

**Comment by OleksandrKvl** [comment]
This question is more about SBE format itself, this library only provides fast implementation of it. The answer depends on your message structure and access pattern. For message with only top-level `field`-s performance should be the same because field offsets are known at compile-time. However, if you add `group`-s or `data` fields, offsets to them are not longer known at compile-time and should be calculated at run-time. Whether this calculation becomes slow or now depends on your access pattern. `sbepp` also provides cursor-based accessors to make accessing of complex messages as fast as possible but they require sequential access. Also don't forget that SBE message has required header so there's a bit of space overhead compared to the raw `struct`.
