### ISSUE TITLE
SBE 2.0

### ISSUE THREAD

**Issue by jodyhagins** [OleksandrKvl/sbepp#67]
What is the plan for supporting SBE v2.0?

**Comment by OleksandrKvl** [comment]
AFAIK SBE 2.0 isn't a thing and from the absence of activity in the SBE repo I think it will never be. Even SBE 1.0 was never officially standardized but it's used by various venues.

Do you know someone who's using 2.0? What are the major improvements or changes it introduces? I can only remember `alignment` attribute.

**Comment by jodyhagins** [comment]
Right, the 2.0 effort hasn't had much love in a while (personal opinion is that trying to go the ISO route is just strapping on leg irons).

I must confess, the question is rooted in a bit of selfishness and laziness.

There are a number of minor changes and some of what I'd call bug fixes.

However, it does have some more important things which allow more ways of modifying a schema without breaking version portability and for porting non-SBE protocols to SBE.

For example, explicit support for `numGroups` and `numVarDataFields` in both `messageHeader` and `groupSizeEncoding`.  Version 1 allows you to specify unique types for each of those, so there are ways to do it yourself, but it does not define how clients should use any extra data fields, so it automatically makes your schema non-standard.

I was wondering, because I just discovered your project.

I have my own somewhat similar implementation, which has been in a private repo, and was recently updated to generate C++20 code, which makes the supporting library much nicer and way simpler.  However, ideally, I'd like to not keep supporting it and use something else.  Yours is as close to what I want to use as I've come across.

I thought about fork/change, but that gets old as well, and at that point I may as well just keep using what I've got.

**Comment by OleksandrKvl** [comment]
The main reason why I never tried to implement SBE 2.0 is because I don't know if it's used by anyone. AFAIK it was more like a prototype rather than something complete. Have you seen SBE 2.0 being used somewhere? I can start looking at it but there should be a real user demand.

> For example, explicit support for numGroups and numVarDataFields in both messageHeader and groupSizeEncoding. Version 1 allows you to specify unique types for each of those, so there are ways to do it yourself, but it does not define how clients should use any extra data fields, so it automatically makes your schema non-standard.

Not sure I fully understand your point here but `numGroups` and `numVarDataFields` are basically useless (though my implementation sets them correctly). That's because there's no way to know `group`/`data` header type and calculate their memory size. To make them work, SBE 2.0 should introduce a fixed `group`/`data` header types for the whole schema or at least per message but this is against SBE 1.0 that allows setting custom header type for each `group`/`data` individually.

**Comment by jodyhagins** [comment]
Must have been on crack...

I'm not sure what I was talking about.  I've been using 2.0-ish since it came out because it addressed issues I had with more flexibility regarding message layout.  However, I just did a side-by-side comparison between the latest ones I could find, and they don't seem much different.

Ignore the idiot behind the curtain.
